export const cultures = [
  {
    name: "Tihar Festival Experience",
    description: "Join locals in celebrating the vibrant festival of lights with music, dances, and rituals.",
    image: "/tihar.jpeg",
    tags: ["festival", "traditional", "celebration"],
    location: "Nationwide",
  },
  {
    name: "Thangka Painting Workshops",
    description: "Learn the ancient art of Tibetan Buddhist Thangka painting with skilled artists.",
    image: "/Thangka Painting Workshops.jpeg",
    tags: ["art", "workshop", "traditional"],
    location: "Kathmandu",
  },
  {
    name: "Newari Cooking Class",
    description: "Discover authentic Newari cuisine by cooking traditional dishes in a local kitchen.",
    image: "/Newari cooking class.jpeg",
    tags: ["food", "workshop", "traditional"],
    location: "Bhaktapur",
  },
  {
    name: "Gai Jatra Festival",
    description: "Participate in the lively Gai Jatra festival, a unique cultural celebration of life and death.",
    image: "/gai jatra.jpeg",
    tags: ["festival", "traditional", "celebration"],
    location: "Kathmandu Valley",
  },
  {
    name: "Patan Durbar Square Cultural Tour",
    description: "Explore ancient palaces, temples, and museums while learning local legends and customs.",
    image: "/Patan Durbar Square.jpg",
    tags: ["heritage", "tour", "traditional"],
    location: "Patan",
  },
  {
    name: "Sherpa Cultural Homestay",
    description: "Stay with a Sherpa family and immerse yourself in their mountain lifestyle and customs.",
    image: "/Sherpa homestay.jpeg",
    tags: ["homestay", "traditional", "community"],
    location: "Everest Region",
  },
  {
    name: "Maithili Folk Dance Workshop",
    description: "Join hands to learn the colorful and rhythmic folk dances of the Maithili community.",
    image: "/Maithili Folk Dance Workshop.jpeg",
    tags: ["dance", "workshop", "traditional"],
    location: "Janakpur",
  },
  {
    name: "Festival of Chhath Puja",
    description: "Experience the sacred Chhath Puja, honoring the Sun God with rituals by the riverside.",
    image: "/Festival of Chhath Puja.jpeg",
    tags: ["festival", "ritual", "traditional"],
    location: "Terai Region",
  },
  {
    name: "Pahadi Folk Music Evening",
    description: "Enjoy live traditional music and songs from the hills of Nepal in an intimate setting.",
    image: "/Pahadi Folk Music Evening.jpeg",
    tags: ["music", "traditional", "performance"],
    location: "Kathmandu Valley",
  },
  {
    name: "Weaving and Handicraft Tour",
    description: "Visit local artisans to see and try traditional weaving and handicraft techniques.",
    image: "/Weaving and Handicraft Tour.jpeg",
    tags: ["craft", "workshop", "traditional"],
    location: "Bhaktapur",
  },
  {
    name: "Indra Jatra Festival",
    description: "Witness the spectacular chariot processions and masked dances in Kathmandu honoring the god Indra.",
    image: "/Indra Jatra Festival.jpeg",
    tags: ["festival", "traditional", "celebration"],
    location: "Kathmandu",
  },
  {
    name: "Tharu Cultural Dance Performance",
    description: "Experience the unique and lively folk dances of the Tharu community in the Terai region.",
    image: "/Tharu Cultural Dance Performance.jpeg",
    tags: ["dance", "performance", "traditional"],
    location: "Terai Region",
  },
  {
    name: "Buddhist Monastery Visit and Meditation",
    description: "Join monks for meditation sessions and explore Buddhist rituals in a serene monastery setting.",
    image: "/Buddhist Monastery Visit and Meditation.jpeg",
    tags: ["spiritual", "ritual", "traditional"],
    location: "Lumbini",
  },
  {
    name: "Maghe Sankranti Celebration",
    description: "Celebrate the harvest festival with traditional foods, songs, and rituals marking the winter solstice.",
    image: "/Maghe Sankranti Celebration.jpeg",
    tags: ["festival", "traditional", "celebration"],
    location: "Nationwide",
  },
  {
    name: "Tamang Heritage Trail",
    description: "Explore Tamang villages, learn their language, customs, and enjoy traditional food and dances.",
    image: "/Tamang Heritage Trail.jpeg",
    tags: ["heritage", "community", "traditional"],
    location: "Langtang Region",
  },
  {
    name: "Kirat Rai Cultural Festival",
    description: "Celebrate the Kirat Rai ethnic group’s vibrant festival with ritual dances and community feasts.",
    image: "/Kirat Rai Cultural Festival.jpeg",
    tags: ["festival", "ethnic", "traditional"],
    location: "Eastern Nepal",
  },
  {
    name: "Nepali Traditional Handloom Weaving",
    description: "Learn about the art of handloom weaving and create your own Nepali fabric souvenir.",
    image: "/Nepali Traditional Handloom Weaving.jpeg",
    tags: ["craft", "workshop", "traditional"],
    location: "Dhading",
  },
  {
    name: "Dashain Festival Celebration",
    description: "Participate in the largest Hindu festival of Nepal, marked by family gatherings, rituals, and animal sacrifices.",
    image: "/Dashain Festival Celebration.jpeg",
    tags: ["festival", "traditional", "celebration"],
    location: "Nationwide",
  },
  {
    name: "Nepali Folk Instrument Workshop",
    description: "Try playing traditional instruments like sarangi, madal, and bansuri with local musicians.",
    image: "/Nepali Folk Instrument Workshop.jpeg",
    tags: ["music", "workshop", "traditional"],
    location: "Kathmandu Valley",
  },
  {
    name: "Madhesi Traditional Attire and Jewelry Tour",
    description: "Discover the vibrant clothing and jewelry customs of the Madhesi people in the southern plains.",
    image: "/Madhesi Traditional Attire and Jewelry Tour.jpeg",
    tags: ["heritage", "fashion", "traditional"],
    location: "Terai Region",
  },
  {
    name: "Kumari Living Goddess Ceremony",
    description: "Witness the rituals surrounding the Kumari, the living goddess, in Kathmandu’s historic squares.",
    image: "/Kumari Living Goddess Ceremony.jpeg",
    tags: ["ritual", "traditional", "spiritual"],
    location: "Kathmandu",
  },
  {
    name: "Limbu Cultural Homestay",
    description: "Stay with the Limbu community and experience their unique customs, language, and cuisine.",
    image: "/Limbu Cultural Homestay.jpeg",
    tags: ["homestay", "community", "traditional"],
    location: "Eastern Nepal",
  },
  {
    name: "Holi Festival Color Celebration",
    description: "Join the exuberant Holi festival where locals throw colored powders and celebrate spring.",
    image: "/Holi Festival Color Celebration.jpeg",
    tags: ["festival", "celebration", "traditional"],
    location: "Nationwide",
  },
  {
    name: "Nepalese Folk Storytelling Night",
    description: "Enjoy evenings of traditional Nepali folk tales and legends narrated by local storytellers.",
    image: "/Nepalese Folk Storytelling Night.jpeg",
    tags: ["performance", "traditional", "community"],
    location: "Kathmandu Valley",
  },
  {
    name: "Kartik Naach Festival",
    description: "Attend this month-long masked dance drama at Patan Durbar Square depicting Hindu epics.",
    image: "/Kartik Naach Festival.jpeg",
    tags: ["festival", "dance", "traditional"],
    location: "Patan",
  },
  {
    name: "Mochi (Leather Craft) Workshop",
    description: "Learn traditional leather crafting techniques used by the Mochi community in Nepal.",
    image: "/Mochi (Leather Craft) Workshop.jpeg",
    tags: ["craft", "workshop", "traditional"],
    location: "Kathmandu",
  },
  {
    name: "Sherpa Throat Singing Performance",
    description: "Experience the haunting and beautiful traditional throat singing unique to Sherpa culture.",
    image: "/Sherpa Throat Singing Performance.jpeg",
    tags: ["music", "performance", "traditional"],
    location: "Everest Region",
  },
  {
    name: "Bisket Jatra Festival",
    description: "Celebrate the New Year with thrilling chariot pulling and ancient rituals in Bhaktapur.",
    image: "/Bisket Jatra Festival.jpeg",
    tags: ["festival", "traditional", "celebration"],
    location: "Bhaktapur",
  },
  {
    name: "Pahadi Wedding Ceremony Experience",
    description: "Witness and participate in a traditional hill region wedding with unique rituals and festivities.",
    image: "/Pahadi Wedding Ceremony Experience.jpeg",
    tags: ["ritual", "traditional", "celebration"],
    location: "Kathmandu Valley",
  },
  {
    name: "Nepalese Paper-making Workshop",
    description: "Create traditional handmade paper (lokta) using age-old techniques with local artisans.",
    image: "/Nepalese Paper-making Workshop.jpeg",
    tags: ["craft", "workshop", "traditional"],
    location: "Kathmandu Valley",
  },
];
