import { Guide } from './types';

export const guides: Guide[] = [
  {
    id: "1",
    name: "Tenzing Norbu",
    location: "Kathmandu Valley",
    languages: ["English", "Nepali", "Hindi"],
    experience: "8 years",
    rating: 4.9,
    price: 45,
    specialties: ["Cultural Tours", "Heritage Sites", "Mountain Views"],
    image: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=500",
    totalReviews: 127,
    verified: true,
    description: "Expert cultural guide specializing in UNESCO World Heritage sites",
    availability: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    responseTime: "Within 2 hours",
    completedTours: 340,
    certifications: ["UNESCO Heritage Guide", "First Aid Certified"],
    aboutMe: "I'm passionate about sharing Nepal's rich cultural heritage with visitors from around the world. With 8 years of experience, I've guided thousands of travelers through the ancient temples and palaces of Kathmandu Valley.",
    services: ["Full Day Tours", "Half Day Tours", "Multi-day Cultural Tours", "Photography Tours"]
  },
  {
    id: "2",
    name: "Pemba Sherpa",
    location: "Everest Region",
    languages: ["English", "Nepali", "Tibetan"],
    experience: "12 years",
    rating: 4.8,
    price: 60,
    specialties: ["Trekking", "Mountaineering", "High Altitude"],
    image: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=500",
    totalReviews: 89,
    verified: true,
    description: "Professional mountain guide with extensive Everest region experience",
    availability: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    responseTime: "Within 1 hour",
    completedTours: 156,
    certifications: ["IFMGA Mountain Guide", "Wilderness First Aid", "High Altitude Rescue"],
    aboutMe: "Born and raised in the Everest region, I've been guiding trekkers and climbers for over 12 years. Safety is my top priority, and I love sharing the beauty of the Himalayas with adventurous souls.",
    services: ["Everest Base Camp Trek", "Island Peak Climbing", "Gokyo Lakes Trek", "Custom Trekking"]
  },
  {
    id: "3",
    name: "Sita Gurung",
    location: "Annapurna Region",
    languages: ["English", "Nepali", "German"],
    experience: "6 years",
    rating: 4.7,
    price: 40,
    specialties: ["Nature Walks", "Village Tours", "Photography"],
    image: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=500",
    totalReviews: 95,
    verified: true,
    description: "Nature enthusiast specializing in eco-tourism and village experiences",
    availability: ["Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    responseTime: "Within 3 hours",
    completedTours: 203,
    certifications: ["Eco-Tourism Guide", "Photography Guide"],
    aboutMe: "I believe in sustainable tourism that benefits local communities. My tours focus on authentic village experiences and capturing the natural beauty of the Annapurna region through photography.",
    services: ["Village Homestays", "Photography Tours", "Nature Walks", "Eco-Tourism"]
  },
  {
    id: "4",
    name: "Raj Thapa",
    location: "Pokhara",
    languages: ["English", "Nepali", "Japanese"],
    experience: "10 years",
    rating: 4.9,
    price: 50,
    specialties: ["Adventure Sports", "Lake Tours", "Paragliding"],
    image: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=500",
    totalReviews: 156,
    verified: true,
    description: "Adventure sports specialist and certified paragliding instructor",
    availability: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    responseTime: "Within 30 minutes",
    completedTours: 445,
    certifications: ["Paragliding Instructor", "Adventure Sports Guide", "Water Sports Certified"],
    aboutMe: "Adrenaline is my middle name! I've been organizing adventure activities in Pokhara for a decade. From paragliding over Phewa Lake to white-water rafting, I ensure safe and thrilling experiences.",
    services: ["Paragliding", "Lake Tours", "Adventure Packages", "Water Sports"]
  },
  {
    id: "5",
    name: "Maya Tamang",
    location: "Langtang Valley",
    languages: ["English", "Nepali", "French"],
    experience: "7 years",
    rating: 4.6,
    price: 42,
    specialties: ["Cultural Immersion", "Homestays", "Local Cuisine"],
    image: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=500",
    totalReviews: 73,
    verified: true,
    description: "Cultural immersion expert with deep knowledge of Tamang traditions",
    availability: ["Monday", "Wednesday", "Thursday", "Friday", "Saturday"],
    responseTime: "Within 4 hours",
    completedTours: 187,
    certifications: ["Cultural Heritage Guide", "Cooking Instructor"],
    aboutMe: "I'm passionate about preserving and sharing Tamang culture. My tours include authentic homestays, traditional cooking classes, and deep cultural exchanges with local families.",
    services: ["Cultural Tours", "Homestay Experiences", "Cooking Classes", "Traditional Crafts"]
  },
  {
    id: "6",
    name: "Bikram Rai",
    location: "Chitwan National Park",
    languages: ["English", "Nepali", "Hindi"],
    experience: "9 years",
    rating: 4.8,
    price: 48,
    specialties: ["Wildlife Safari", "Jungle Walks", "Bird Watching"],
    image: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=500",
    totalReviews: 112,
    verified: true,
    description: "Wildlife expert and naturalist with extensive jungle experience",
    availability: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    responseTime: "Within 2 hours",
    completedTours: 298,
    certifications: ["Wildlife Guide", "Naturalist", "Jungle Safety Expert"],
    aboutMe: "The jungle is my second home. I've spent 9 years studying and guiding visitors through Chitwan's incredible biodiversity. Every safari is an adventure filled with wildlife encounters and natural wonders.",
    services: ["Jungle Safari", "Bird Watching Tours", "Wildlife Photography", "Nature Education"]
  }
];

export const locations = [
  "All Locations",
  "Kathmandu Valley",
  "Everest Region",
  "Annapurna Region",
  "Pokhara",
  "Langtang Valley",
  "Chitwan National Park"
];

export const specialties = [
  "All Specialties",
  "Cultural Tours",
  "Trekking",
  "Adventure Sports",
  "Wildlife Safari",
  "Photography",
  "Village Tours",
  "Heritage Sites",
  "Nature Walks"
];

export const experienceLevels = [
  "All Experience",
  "5+ years",
  "8+ years",
  "10+ years"
];